# This is a  basic workflow to help you get started with Actions

name: CI

on:
  push:
  schedule:
    - cron: '*/20 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.12'

      - name: Set  TimeZone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date

      # Runs a set of commands using the runners shell
      - name: Run  test
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytz
          python cls_news.py
          echo test, and deploy your project.
      - name: commit database 
        run: | 
          git config user.name hhackk
          git config user.email hack163com@163.com
          git add .
          git commit -m "database" || echo ok1
          git push -f|| echo ok3
          
      - uses: actions/checkout@v2
        with:
           ref: gh-pages
      - name: copy
        run: |
          cp /tmp/*_cls_news.json cls_data/
          git config user.name hhackk
          git config user.email hack163com@163.com
          git add .
          git commit -m "add data" || echo ok
          git push || echo ok
